import { useRouter } from 'next/router';
import { NextSeo } from 'next-seo';
import { isMultiLanguage } from '../../lib/isMultiLanguage.js';
import { sortDate } from '@pantheon-systems/nextjs-kit';
import {
	getCurrentLocaleStore,
	globalDrupalStateStores,
} from '../../lib/stores';

import { ArtistGridItem } from '../../components/grid';
import { withGrid } from '@pantheon-systems/nextjs-kit';
import PageHeader from '../../components/page-header';
import Layout from '../../components/layout';

export default function SSRArtistsListTemplate({
	sortedArtists,
    footerMenu,
	hrefLang,
	multiLanguage,
}) {
	const { locale } = useRouter();
	const ArtistGrid = withGrid(ArtistGridItem);
	return (
		<Layout footerMenu={footerMenu}>
			<NextSeo
				title="Decoupled Next Drupal Demo"
				description="Generated by create next app."
				languageAlternates={hrefLang || false}
			/>
			<PageHeader title="Artists" />
			<section>
				<ArtistGrid
					data={sortedArtists}
					contentType="artists"
					multiLanguage={multiLanguage}
					locale={locale}
				/>
			</section>
		</Layout>
	);
}

export async function getServerSideProps(context) {
	try {
		const origin = process.env.NEXT_PUBLIC_FRONTEND_URL;
		const { locale, locales } = context;
		// if there is more than one language in context.locales,
		// assume multilanguage is enabled.
		const multiLanguage = isMultiLanguage(locales);
		const hrefLang = locales.map((locale) => {
			return {
				hrefLang: locale,
				href: origin + '/' + locale,
			};
		});

		const store = getCurrentLocaleStore(locale, globalDrupalStateStores);

		const artists = await store.getObject({
			objectName: 'node--artist',
			res: context.res,
			refresh: true,
			params: 'include=field_media_image.field_media_image',
		});

		const footerMenu = await store.getObject({
			objectName: 'menu_items--main',
			res: context.res,
			refresh: true,
		});

		if (!artists) {
			throw new Error(
				'No artists returned. Make sure the objectName and params are valid!',
			);
		}

		const sortedArtists = sortDate({
			data: artists,
			key: 'changed',
			direction: 'desc',
		});

		return {
			props: {
				sortedArtists,
				hrefLang,
				multiLanguage,
				footerMenu,
			},
		};
	} catch (error) {
		console.error('Unable to fetch data for artist page: ', error);
		return {
			notFound: true,
		};
	}
}