import { NextSeo } from 'next-seo';
import { sortDate } from '@pantheon-systems/nextjs-kit';
import { isMultiLanguage } from '../lib/isMultiLanguage';
import { getCurrentLocaleStore, globalDrupalStateStores } from '../lib/stores';

import { ArticleGridItem } from '../components/grid';
import { ArtistGridItem } from '../components/grid';
import { EventGridItem } from '../components/grid';
import { withGrid } from '@pantheon-systems/nextjs-kit';
import Image from 'next/image';
import Layout from '../components/layout';

export default function HomepageTemplate({
	sortedArticles,
	sortedArtists,
	sortedEvents,
	footerMenu,
	hrefLang,
	multiLanguage,
}) {
	const ArticleGrid = withGrid(ArticleGridItem);
	const ArtistGrid = withGrid(ArtistGridItem);
	const EventsGrid = withGrid(EventGridItem);

	return (
		<Layout footerMenu={footerMenu}>
			<NextSeo
				title="Decoupled Next Drupal Demo"
				description="Generated by create next app."
				languageAlternates={hrefLang || false}
			/>
			<>
				<section>
					<ArticleGrid
						data={sortedArticles}
						contentType="articles"
						multiLanguage={multiLanguage}
					/>
				</section>
				<section>
					<h3>Artists </h3>
					<ArtistGrid
						data={sortedArtists}
						contentType="artists"
						multiLanguage={multiLanguage}
					/>
				</section>
				<section>
					<h3>Events</h3>
					<EventsGrid
						data={sortedEvents}
						contentType="events"
						multiLanguage={multiLanguage}
					/>
				</section>
			</>
		</Layout>
	);
}

export async function getServerSideProps(context) {
	const origin = process.env.NEXT_PUBLIC_FRONTEND_URL;
	const { locales } = context;
	// if there is more than one language in context.locales,
	// assume multilanguage is enabled.
	const multiLanguage = isMultiLanguage(locales);
	const hrefLang = locales.map((locale) => {
		return {
			hrefLang: locale,
			href: origin + '/' + locale,
		};
	});

	try {
		const store = getCurrentLocaleStore(
			context.locale,
			globalDrupalStateStores,
		);

		const articles = await store.getObject({
			objectName: 'node--article',
			params: 'include=field_media_image.field_media_image',
			refresh: true,
			res: context.res,
		});

		const artists = await store.getObject({
			objectName: 'node--artist',
			params: 'include=field_media_image.field_media_image',
			refresh: true,
			res: context.res,
		});

		const events = await store.getObject({
			objectName: 'node--event',
			params: 'include=field_venue',
			refresh: true,
			res: context.res,
		});

		if (!articles) {
			throw new Error(
				'No articles returned. Make sure the objectName and params are valid!',
			);
		}

		if (!artists) {
			throw new Error(
				'No artists returned. Make sure the objectName and params are valid!',
			);
		}

		if (!events) {
			throw new Error(
				'No events returned. Make sure objectName and params are valid!',
			);
		}

		const sortedArticles = sortDate({
			data: articles,
			key: 'changed',
			direction: 'desc',
		});

		const sortedArtists = sortDate({
			data: artists,
			key: 'changed',
			direction: 'desc',
		});

		const sortedEvents = sortDate({
			data: events,
			key: 'changed',
			direction: 'desc',
		});

		const footerMenu = await store.getObject({
			objectName: 'menu_items--main',
			refresh: true,
			res: context.res,
		});

		return {
			props: { sortedArticles, sortedArtists, hrefLang, multiLanguage, footerMenu },
		};
	} catch (error) {
		console.error('Unable to fetch data for articles page: ', error);
		console.error('Unable to fetch data for artists page: ', error);
		console.error('Unable to fetch data for events page: ', error);
		return {
			notFound: true,
		};
	}
}
